In [2]:
import numpy as np


In [6]:
a1 = np.array([1,2,3])
type(a1)

numpy.ndarray

In [9]:
a2 = np.arange(10)
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
a3 = np.zeros((2,3))
a4 = np.ones((2,3))

In [14]:
from IPython.display import display
display(a3)
display(a4)

array([[0., 0., 0.],
       [0., 0., 0.]])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
a5 = np.linspace(0,1,11)
display(a5)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [16]:
type(a5)

numpy.ndarray

In [17]:
a5.dtype

dtype('float64')